# NUMPY

## Installing Numpy

In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


## Importing Numpy

In [3]:
import numpy as np

In [4]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


## Checking Numpy Version

In [5]:
print(np.__version__)

2.3.5


## Create a Numpy ndarray Object

In [6]:
arr = np.array([1,2,3,4,5])
# printing type of arr object
print(type(arr))
print(arr)
# creating array from list with type float
a = np.array([[1,2,4], [5,8,7]], dtype = 'float')
print("Array created using passed list:\n", a)

<class 'numpy.ndarray'>
[1 2 3 4 5]
Array created using passed list:
 [[1. 2. 4.]
 [5. 8. 7.]]


## Use a tuple to create a NumPy array

In [7]:
arr = np.array((1,3,2,3,4,5))
print(type(arr))
print(arr)

<class 'numpy.ndarray'>
[1 3 2 3 4 5]


## All Zero Array

## Create a 0-D array with value 42

0-D or scalars are the elements in an array. Each value in an array is a 0-D array.

In [8]:
arr = np.array(42)
print(arr)

42


## 1-D Arrays

An array that has 0-D arrays as its elements is called uni-dimensional or 1 D-array.
These are the most common and basic arrays.

In [9]:
arr = np.array([1,2,3,4])
print(arr)

[1 2 3 4]


## 2-D Arrays

An array that has 1-D arrays as its elements is called a 2-D array.
These are often used to represent matrix or 2nd order tensors.

In [10]:
arr = np.array([[1,2,3,4], [5,6,7,8]])
print(type(arr))
print(arr)

<class 'numpy.ndarray'>
[[1 2 3 4]
 [5 6 7 8]]


## 3-D Arrays

An array that has 2-D arrys (matrices) as its elemments is called 3-D array.
These are often used to represent a 3rd order tensor.

In [11]:
arr = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [9,10,11]]])
print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [ 9 10 11]]]


## Check Number of Dimensions

In [12]:
a = np.array(42)
b = np.array([1,2,3,4])
c = np.array([[1,2,3,4], [5,6,7,8]])
d = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [9,10,11]]])

# printing array dimensions
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


## Shape of array

In [13]:
shape = arr.shape
print(shape)

print("Shape of array:",a.shape)
print("Shape of array:",b.shape)
print("Shape of array:",c.shape)
print("Shape of array:",d.shape)

(2, 2, 3)
Shape of array: ()
Shape of array: (4,)
Shape of array: (2, 4)
Shape of array: (2, 2, 3)


## Type of elements in array

In [14]:
print("Array stores elements of type:", arr.dtype)

Array stores elements of type: int64


## Accessing Array elements 

In [15]:
numbers = np.array([10,20,30,40])
print(numbers[0])
print(numbers[1])

10
20


## Higher Dimensional Arrays

An array can have any number of dimensions.
When the array is created, you can define the number of dimensions by using the ndmin argument.


In [16]:
arr = np.array([1, 2, 3, 4], ndmin=7)
print(arr)
print("Number of dimensions :", arr.ndim)

[[[[[[[1 2 3 4]]]]]]]
Number of dimensions : 7


In [17]:
arr = np.array([1,2,3,4,5,6,7], ndmin=5)
print(arr)
print("Number of dimensions :", arr.ndim)

[[[[[1 2 3 4 5 6 7]]]]]
Number of dimensions : 5


### 1. Create an array with all zeroes

In [32]:
# 3X4 mtrix of zeros
c = np.zeros((3,4))
print("An array initialized as matrix of all zeros:\n", c)

# 3X4X2 array of zeros
c = np.zeros((3,4,2))
print("An array initialized with all zeros:\n", c)

An array initialized as matrix of all zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
An array initialized with all zeros:
 [[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]]


### 2. Create a constant value array of complex type 

In [19]:
d = np.full((3,3),6, dtype = 'complex')
print("An array initialized with all 6s. Array type is complex:\n", d)


An array initialized with all 6s. Array type is complex:
 [[6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]]


### 3. Create an array with random values

In [20]:
e = np.random.random((2,2))
print("A random array:\n", e)

A random array:
 [[0.61480158 0.12662827]
 [0.96165    0.49078546]]


### 4. Creating a 3x4 array with all ones

In [21]:
f = np.ones((3,4))
print("An array intialized with all ones:\n", f)

An array intialized with all ones:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### 5. Creating Identity Matrix

In [22]:
g = np.eye(3)
print("Identity Matrix Array:\n", g)

Identity Matrix Array:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [23]:
# To see documentation of any method
np.arange?

Docstring:
arange([start,] stop[, step,], dtype=None, *, device=None, like=None)

Return evenly spaced values within a given interval.

``arange`` can be called with a varying number of positional arguments:

* ``arange(stop)``: Values are generated within the half-open interval
  ``[0, stop)`` (in other words, the interval including `start` but
  excluding `stop`).
* ``arange(start, stop)``: Values are generated within the half-open
  interval ``[start, stop)``.
* ``arange(start, stop, step)`` Values are generated within the half-open
  interval ``[start, stop)``, with spacing between values given by
  ``step``.

For integer arguments the function is roughly equivalent to the Python
built-in :py:class:`range`, but returns an ndarray rather than a ``range``
instance.

When using a non-integer step, such as 0.1, it is often better to use
`numpy.linspace`.

See the Warning sections below for more information.

Parameters
----------
start : integer or real, optional
    Start of interval.

In [24]:
np.linspace?

Signature:      
np.linspace(
    start,
    stop,
    num=50,
    endpoint=True,
    retstep=False,
    dtype=None,
    axis=0,
    *,
    device=None,
)
Call signature:  np.linspace(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function linspace at 0x000002CB87271EE0>
File:            c:\users\vaishnavi\anaconda3\lib\site-packages\numpy\_core\function_base.py
Docstring:      
Return evenly spaced numbers over a specified interval.

Returns `num` evenly spaced samples, calculated over the
interval [`start`, `stop`].

The endpoint of the interval can optionally be excluded.

.. versionchanged:: 1.20.0
    Values are rounded towards ``-inf`` instead of ``0`` when an
    integer ``dtype`` is specified. The old behavior can
    still be obtained with ``np.linspace(start, stop, num).astype(int)``

Parameters
----------
start : array_like
    The starting value of the sequence.
stop : array_like
    The end value of the sequence, unless `endpoint` is set to Fa

### 6. Create a sequence of integers from 0 to 30 with steps of 5.

In [25]:
h = np.arange(0,30,5)
print("\n A Sequential array with steps of 5:\n", h)


 A Sequential array with steps of 5:
 [ 0  5 10 15 20 25]


### 7. Create a sequence of 10 values in range 0 to 5 

In [26]:
i = np.arange(0,5,10)
print("\n A Sequential array with 10 values between 0 and 5:\n", i)

# Since the step (10) is larger than the range (0 to 5), 
# NumPy includes only the starting value 0 and then stops because the next value (10) is already greater than 5.

i = np.linspace(0,5,10)
print("\n A Sequential array with 10 values between 0 and 5:\n", i)

# using linspace, 10 values are created between 0 and 5
# np.arange(start, stop, step) → step size is specified.
# np.linspace(start, stop, num) → number of values is specified


 A Sequential array with 10 values between 0 and 5:
 [0]

 A Sequential array with 10 values between 0 and 5:
 [0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


### 8. Reshaping 3x4 array to 2x2x3 array

In [27]:
arr = np.array([[1,2,3,4],
               [5,2,3,2],
               [1,2,0,1]])
newArr = arr.reshape(2,2,3)
print("\n Original array:\n", arr)
print("\n Reshaped array:\n", newArr)


 Original array:
 [[1 2 3 4]
 [5 2 3 2]
 [1 2 0 1]]

 Reshaped array:
 [[[1 2 3]
  [4 5 2]]

 [[3 2 1]
  [2 0 1]]]


### 9. Flatten Array

In [28]:
arr = np.array([[1,2,3],[4,5,6]])
f1arr = arr.flatten()
print("\n Original Array:\n", arr)
print("\n Flattened Array:\n", f1arr)


 Original Array:
 [[1 2 3]
 [4 5 6]]

 Flattened Array:
 [1 2 3 4 5 6]


### 10. Create a null vector of size 10

In [29]:
null_vector = np.zeros(10)
print("Null vector with 10 zeros:\n", null_vector)

Null vector with 10 zeros:
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [30]:
null_vector = np.zeros(10, dtype=int)
print("Null vector with 10 zeros of int type:\n", null_vector)

Null vector with 10 zeros of int type:
 [0 0 0 0 0 0 0 0 0 0]


#### 4.  How to find the memory size of any array

In [45]:
arr = np.array([1,2,3,4,5])
print(arr.nbytes)

print("Size of one element:", arr.itemsize, "bytes")
print("Number of elements:", arr.size)
print("Total memory:", arr.nbytes, "bytes")

# arr.nbytes == arr.size * arr.itemsize
# Total Memory = Number of Elements × Size of One Element

# Example with 2-D Array
arr = np.array([[1,2,3],
               [5,6,7]])
print(arr.nbytes)

print("Size of one element:", arr.itemsize)
print("Number of elements:", arr.size)
print("Total memory:", arr.nbytes)

40
Size of one element: 8 bytes
Number of elements: 5
Total memory: 40 bytes
48
Size of one element: 8
Number of elements: 6
Total memory: 48


#### 5.  How to get the documentation of the numpy add function from the command line? 

In [49]:
help(np.add)
#np.add?
#np.add??

Help on ufunc in module numpy:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

    Add arguments element-wise.

    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

#### 6.  Create a null vector of size 10 but the fifth value which is 1


In [52]:
arr = np.zeros(10, dtype=int)
arr[4] = 1   # NumPy uses 0-based indexing
print(arr)

[0 0 0 0 1 0 0 0 0 0]


#### 7.  Create a vector with values ranging from 10 to 49

In [53]:
arr = np.arange(10,50)
print(arr)

# Starts from 10 and Stops 

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last)

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\]

#### 11. Create a 3x3 identity matrix

#### 12. Create a 3x3x3 array with random values

#### 13. Create a 10x10 array with random values and find the minimum and maximum values

#### 14. Create a random vector of size 30 and find the mean value

#### 15. Create a 2d array with 1 on the border and 0 inside

#### 16. How to add a border (filled with 0's) around an existing array?

#### 17. What is the result of the following expression?

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?