# NUMPY

## Installing Numpy

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


## Importing Numpy

In [2]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


## Checking Numpy Version

In [4]:
print(np.__version__)

2.3.5


## Create a Numpy ndarray Object

In [5]:
arr = np.array([1,2,3,4,5])
# printing type of arr object
print(type(arr))
print(arr)
# creating array from list with type float
a = np.array([[1,2,4], [5,8,7]], dtype = 'float')
print("Array created using passed list:\n", a)

<class 'numpy.ndarray'>
[1 2 3 4 5]
Array created using passed list:
 [[1. 2. 4.]
 [5. 8. 7.]]


## Use a tuple to create a NumPy array

In [6]:
arr = np.array((1,3,2,3,4,5))
print(type(arr))
print(arr)

<class 'numpy.ndarray'>
[1 3 2 3 4 5]


## Create a 0-D array with value 42

0-D or scalars are the elements in an array. Each value in an array is a 0-D array.

In [7]:
arr = np.array(42)
print(arr)

42


## 1-D Arrays

An array that has 0-D arrays as its elements is called uni-dimensional or 1 D-array.
These are the most common and basic arrays.

In [8]:
arr = np.array([1,2,3,4])
print(arr)

[1 2 3 4]


## 2-D Arrays

An array that has 1-D arrays as its elements is called a 2-D array.
These are often used to represent matrix or 2nd order tensors.

In [9]:
arr = np.array([[1,2,3,4], [5,6,7,8]])
print(type(arr))
print(arr)

<class 'numpy.ndarray'>
[[1 2 3 4]
 [5 6 7 8]]


## 3-D Arrays

An array that has 2-D arrys (matrices) as its elemments is called 3-D array.
These are often used to represent a 3rd order tensor.

In [10]:
arr = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [9,10,11]]])
print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [ 9 10 11]]]


## Check Number of Dimensions

In [11]:
a = np.array(42)
b = np.array([1,2,3,4])
c = np.array([[1,2,3,4], [5,6,7,8]])
d = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [9,10,11]]])

# printing array dimensions
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


## Shape of array

In [12]:
shape = arr.shape
print(shape)

print("Shape of array:",a.shape)
print("Shape of array:",b.shape)
print("Shape of array:",c.shape)
print("Shape of array:",d.shape)

# Create an array with 5 dimensions using ndmin using a vector with values 1,2,3,4.
arr = np.array([1,2,3,4], ndmin=5)
print("shape of array:", arr.shape)

(2, 2, 3)
Shape of array: ()
Shape of array: (4,)
Shape of array: (2, 4)
Shape of array: (2, 2, 3)
shape of array: (1, 1, 1, 1, 4)


## Array Reshaping

In [13]:
## Reshape from 1-D to 2-D
arr1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
# newarr = arr.reshape(4,3)
newarr = arr1.reshape(12)
print(newarr)

## Reshape from 1-D to 3-D
# newarr = arr.reshape(2,3,2)
print(newarr)

# We cannot reshape the array into any shape
# newarr = arr.reshape(3,3)  # 3x3 = 9
# print(newarr)   # Gives ValueError that it cannot reshape array of size 12 into shape (3,3)

# Check if the returned array is a copy or a view:
arr2 = np.array([1,2,3,4,5,6,7,8])
# print(arr.reshape(2,4).base)
# This example returns a original array, so it is a view.

# You are allowed to have one "unknown" dimension. 
# Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.
# Pass -1 as the value, and NumPy will calculate this number for you.
# newarr = arr2.reshape(2,2,-1)
# print(newarr)

# NOTE :- We cannot pass -1 to more than one dimension.


## Flattening the arrays (2-D to 1-D array)
# Flattening array means converting a multidimensional array into a 1D array.
# use reshape(-1) to do this.
arr = np.array([[1,2,3],[4,5,6]])
newarr = arr.reshape(-1)
print(newarr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[1 2 3 4 5 6]


## Data Type of an Array

In [14]:
print("Array stores elements of type:", arr.dtype)

arr = np.array(["apple", "banana", "cherry"])
print(arr.dtype)


# Creating Arrays with a Defined Data type
arr = np.array([1,2,3,4], dtype='S')   # S -> String
print(arr.dtype)

arr = np.array([1,2,3,4], dtype='i4')   # i -> integer, having 4 bytes integer.
print(arr.dtype)


# Converting Data type on Existing Arrays
arr = np.array([1.1,2.1,3.1])
newarr = arr.astype('i')
print(newarr)
print(newarr.dtype)

newarr = arr.astype(int)
print(newarr.dtype)

arr = np.array([1,0,3])
newarr = arr.astype(bool)
print(newarr)
print(newarr.dtype)

Array stores elements of type: int64
<U6
|S1
int32
[1 2 3]
int32
int64
[ True False  True]
bool


## Accessing Array elements 

In [15]:
# Access Array Elements
numbers = np.array([10,20,30,40])
print(numbers[0])
print(numbers[1])
print(numbers[2] + numbers[3])

# Acess 2-D Arrays
arr = np.array([[1,2,3,4], [5,6,7,8]])
print("2nd element on 1st row:", arr[0,1])
print("4th element on 2nd row:", arr[1,3])

# Access 3-D Arrays
arr = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])
print(arr[0, 1, 2])

# Negative Indexing 
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print("Last element from 2nd dim:", arr[1,-1])

10
20
70
2nd element on 1st row: 2
4th element on 2nd row: 8
6
Last element from 2nd dim: 10


## Array Slicing

In [16]:
arr = np.array([1,3,4,5,6,6,5])
print(arr[1:5])   # the result includes the star index but excludes the end index
print(arr[4:])    # slice elements from index 4 to the end of the array
print(arr[:4])    # slice elements from the beginning to index 4 (not included)
print(arr[1:5:2]) # use step value to determine the step of the slicing
print(arr[::2])   # return every other element from the entire array

# Negative Slicing
arr = np.array([1,2,3,4,5,6])
print(arr[-3:-1])

#Slicing 2-D Arrays
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])
print(arr[0:2, 2])
print(arr[0:2, 1:4])

[3 4 5 6]
[6 6 5]
[1 3 4 5]
[3 5]
[1 4 6 5]
[4 5]
[7 8 9]
[3 8]
[[2 3 4]
 [7 8 9]]


## NumPy Array Copy vs View

In [17]:
# The copy owns the data and any changes made to the copy will not affect original array,
# and any changes made to the original array will not affect the copy.
# The copy SHOULD NOT be affected by the changes made to the original array.
arr = np.array([1,2,3,4,5])
x = arr.copy()
arr[0] = 43
print(arr)
print(x)

#The view SHOULD be affected by the changes made to the original array.
# The view does not own the data and any changes made to the view will affect the original array, 
# and any changes made to the original array will affect the view.
# The original array SHOULD be affected by the changes made to the view.
x = arr.view()
arr[0] = 42
print(arr)
print(x)

# Make Changes in the VIEW:
arr = np.array([1,2,3,4,5])
x = arr.view()
x[0] = 31
print(arr)
print(x)
# The original array SHOULD be affected by the changes made to the view.

# Check if Array owns its Data

# Every NumPy array has the attribute base that returns None if the array owns the data.
# Otherwise, the base  attribute refers to the original object.
# The copy returns None.
# The view returns the original array.
arr = np.array([1,2,3,4,5,6])
x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

[43  2  3  4  5]
[1 2 3 4 5]
[42  2  3  4  5]
[42  2  3  4  5]
[31  2  3  4  5]
[31  2  3  4  5]
None
[1 2 3 4 5 6]


## Higher Dimensional Arrays

An array can have any number of dimensions.
When the array is created, you can define the number of dimensions by using the ndmin argument.


In [18]:
arr = np.array([1, 2, 3, 4], ndmin=7)
print(arr)
print("Number of dimensions :", arr.ndim)

[[[[[[[1 2 3 4]]]]]]]
Number of dimensions : 7


In [19]:
arr = np.array([1,2,3,4,5,6,7], ndmin=5)
print(arr)
print("Number of dimensions :", arr.ndim)

[[[[[1 2 3 4 5 6 7]]]]]
Number of dimensions : 5


## Iterating Arrays

In [20]:
# Iterating arrays means going through elements one by one.
# As we deal with multi dimensional arrays, we can do this by for loop of python.
# If we iterate on a 1-D array it will go through each element one by one.
arr1 = np.array([1,2,3])
for x in arr1:
    print(x)


## Iterating 2-D arrays
# In a 2-D array it will go through all the rows.
arr2 = np.array([[1,2,3], [4,5,6]])
for x in arr2:
    print(x)

# If we iterate on a n-D array it will go through n-1th dimension one by one.
# To return the actual values, the scalars, we have to iterate the arrays in each dimension.
for x in arr2:
    for y in x:
        print(y)


## Iterating 3-D arrays
# In a 3-D array it will go through all the 2-D arrays.
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in arr3:
    print(x)

# To return the actual values, the scalars, we have to iterate the arrays in each dimension.
for x in arr3:
    for y in x:
        for z in y:
            print(z)



1
2
3
[1 2 3]
[4 5 6]
1
2
3
4
5
6
[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
1
2
3
4
5
6
7
8
9
10
11
12


## Joining Arrays in NumPy

In [21]:
# Joining means putting contents of two or more arrays in a single array.
# In SQL we join tables based on a key, whereas in NumPy we join arrays by axes.
# We pass a sequence of arrays that we want to join to the concatenate() function, along with the axis.
# If axis is not explicitly passed, it is taken as 0.

# Join two arrays:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.concatenate((arr1, arr2))
print(arr)

# Join two 2-D arrays along rows(axis=1):
arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([[5,6], [7,8]])
arr = np.concatenate((arr1, arr2), axis=0)
print(arr)
arr = np.concatenate((arr1, arr2), axis=1)
print(arr)


# Joining arrays using Stack Functions

# Stacking is same as concatenation, the only difference is that stacking is done along a new axis.
# We can concatenate two 1-D arrays along the second axis which would result in putting them one over the other, ie. Stacking.
# We pass a sequence of arrays that we want to join to the stack() method along with the axis.
# If axis is not explicitly passed it is taken as 0.

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.stack((arr1, arr2), axis=1)
print("Using Stack function:-\n",arr)

# Stacking along rows :- NumPy provides a Helper function hstack() to stack along rows.
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.hstack((arr1, arr2))
print("Using hstack():-\n", arr)

# Stacking along columns :- NumPy provides a Helper function vstack() to stack along columns.
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.vstack((arr1, arr2))
print("Using vstack():-\n", arr)

# Stacking along Height(depth) :- NumPy provides a Helper function dstack() to stack along height, which is the same as depth.
arr1 = np.array([1,3,5])
arr2 = np.array([2,4,6])
arr = np.dstack((arr1, arr2))
print("Using dstack():-\n", arr)

[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]
Using Stack function:-
 [[1 4]
 [2 5]
 [3 6]]
Using hstack():-
 [1 2 3 4 5 6]
Using vstack():-
 [[1 2 3]
 [4 5 6]]
Using dstack():-
 [[[1 2]
  [3 4]
  [5 6]]]


## Splitting NumPy Arrays

In [22]:
# Splitting is reverse operation of joining
# Joining merges multiple arrays into one and Splittinf breaks one array into multiple.
# We use array_split() for splitting arrays, we pass it the array we want to split and the number of splits.

# Split the array in 3 parts:
arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr, 3)
print(newarr)  # The return array is a list containing three arrays.

# If the array has less elements than required, it will adjust from the end accordingly.
newarr1 = np.array_split(arr,4)
print(newarr1)
# We also have the method split() available but it will not adjust the elements when elements are less in source array for splitting, array_split() worked properly bt split() would fail.

# Access the splitted arrays:
newarr2 = np.array_split(arr, 3)
print(newarr2[0])
print(newarr2[1])
print(newarr2[2])

# Split the 2-D array into three 2-D arrays.
arr1 = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12], [13,14,15], [16,17,18]])

newarr3 = np.array_split(arr, 3)
print(newarr3)

# Split the 2-D array into three 2-D arrays along columns.
newarr4 = np.array_split(arr1, 3, axis=1)
print(newarr4)

# alternate solution is using hsplit() opposite of hstack(),
# use the hsplit() method to split the 2-D array into three 2-D arrays along columns.
newarr5 = np.hsplit(arr1, 3)
print(newarr5)
# Similarly, vstack() and dstack() are available as vsplit() amd dsplit().

[array([1, 2]), array([3, 4]), array([5, 6])]
[array([1, 2]), array([3, 4]), array([5]), array([6])]
[1 2]
[3 4]
[5 6]
[array([1, 2]), array([3, 4]), array([5, 6])]
[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]
[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


## Sorting Arrays in NumPy

In [23]:
# The NumPy ndarray object has a function called sort(), that will sort a specified array.

arr = np.array([3, 2, 0, 1])
print(np.sort(arr))
# This method returns a copy of the array, leaving the original array unchanged.

# Sort arrays of strings(alphabetically)
arr1 = np.array(['banana', 'cherry', 'apple'])
print(np.sort(arr1))

# Sort a boolean array
arr2 = np.array([True, False, True])
print(np.sort(arr2))

# Sorting a 2-D array
arr3 = np.array([[3,2,4], [5, 0, 1]])
print(np.sort(arr3))

[0 1 2 3]
['apple' 'banana' 'cherry']
[False  True  True]
[[2 3 4]
 [0 1 5]]


## NumPy Searching Arrays

In [24]:
# Search an array for a certain value, and return the indexes that get a match.
# To search an array, use the where() method.

arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4)
print(x)


# The example above will return a tuple: (array([3, 5, 6],)
# which means that the value 4 is present at index 3, 5 and 6.

(array([3, 5, 6]),)


In [60]:
# Find the indexes where the values are odd:

arr1 = np.array([10, 14, 93, 41, 8, 7])
x1 = np.where(arr1 % 2 == 1)
print("indexes where the values are odd:-\n", x1)

# Find the indexes where the values are even: 
arr2 = np.array([10, 14, 93, 41, 8, 7])
x2 = np.where(arr2 % 2 == 0)
print("indexes where the values are even:-\n", x2)

indexes where the values are odd:-
 (array([2, 3, 5]),)
indexes where the values are even:-
 (array([0, 1, 4]),)


In [67]:
# Search Sorted Method
# searchsorted() which performs a binary search in the array, 
# and returns the index where the specified value would be inserted to maintain the seach order.
# searchsorted() method is assumed to be used on sorted arrays.

arr3 = np.array([6, 7, 8, 9])
x3 = np.searchsorted(arr3, 7)
print(x3)

# Search from the Right side
arr4 = np.array([6, 7, 8, 9])
x4 = np.searchsorted(arr4, 7, side='right')
print(x4)



1
2


## Filtering Arrays in NumPy

##### Getting some elements out of an existing array and creating a new array out of them is called filtering.
##### In NumPy, you filter an array using a boolean index list.

##### A boolean index list is a list of booleans corresponding to indexes in the array.

##### If the value at an index is True that element is contained in the filtered array,
##### If the value at an index is False that element is excluded from the filtered array.

### 1. Create an array with all zeroes

In [25]:
# 3X4 mtrix of zeros
c = np.zeros((3,4))
print("An array initialized as matrix of all zeros:\n", c)

# 3X4X2 array of zeros
c = np.zeros((3,4,2))
print("An array initialized with all zeros:\n", c)

An array initialized as matrix of all zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
An array initialized with all zeros:
 [[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]]


### 2. Create a constant value array of complex type 

In [26]:
d = np.full((3,3),6, dtype = 'complex')
print("An array initialized with all 6s. Array type is complex:\n", d)


An array initialized with all 6s. Array type is complex:
 [[6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]]


### 3. Create an array with random values

In [27]:
e = np.random.random((2,2))
print("A random array:\n", e)

A random array:
 [[0.90687694 0.47935985]
 [0.56850059 0.66909044]]


### 4. Creating a 3x4 array with all ones

In [28]:
f = np.ones((3,4))
print("An array intialized with all ones:\n", f)

An array intialized with all ones:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### 5. Creating Identity Matrix

In [29]:
g = np.eye(3)
print("Identity Matrix Array:\n", g)

Identity Matrix Array:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [30]:
# To see documentation of any method
np.arange?

Docstring:
arange([start,] stop[, step,], dtype=None, *, device=None, like=None)

Return evenly spaced values within a given interval.

``arange`` can be called with a varying number of positional arguments:

* ``arange(stop)``: Values are generated within the half-open interval
  ``[0, stop)`` (in other words, the interval including `start` but
  excluding `stop`).
* ``arange(start, stop)``: Values are generated within the half-open
  interval ``[start, stop)``.
* ``arange(start, stop, step)`` Values are generated within the half-open
  interval ``[start, stop)``, with spacing between values given by
  ``step``.

For integer arguments the function is roughly equivalent to the Python
built-in :py:class:`range`, but returns an ndarray rather than a ``range``
instance.

When using a non-integer step, such as 0.1, it is often better to use
`numpy.linspace`.

See the Warning sections below for more information.

Parameters
----------
start : integer or real, optional
    Start of interval.

In [31]:
np.linspace?

Signature:      
np.linspace(
    start,
    stop,
    num=50,
    endpoint=True,
    retstep=False,
    dtype=None,
    axis=0,
    *,
    device=None,
)
Call signature:  np.linspace(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function linspace at 0x0000018CA823DEE0>
File:            c:\users\vaishnavi\anaconda3\lib\site-packages\numpy\_core\function_base.py
Docstring:      
Return evenly spaced numbers over a specified interval.

Returns `num` evenly spaced samples, calculated over the
interval [`start`, `stop`].

The endpoint of the interval can optionally be excluded.

.. versionchanged:: 1.20.0
    Values are rounded towards ``-inf`` instead of ``0`` when an
    integer ``dtype`` is specified. The old behavior can
    still be obtained with ``np.linspace(start, stop, num).astype(int)``

Parameters
----------
start : array_like
    The starting value of the sequence.
stop : array_like
    The end value of the sequence, unless `endpoint` is set to Fa

### 6. Create a sequence of integers from 0 to 30 with steps of 5.

In [32]:
h = np.arange(0,30,5)
print("\n A Sequential array with steps of 5:\n", h)


 A Sequential array with steps of 5:
 [ 0  5 10 15 20 25]


### 7. Create a sequence of 10 values in range 0 to 5 

In [33]:
i = np.arange(0,5,10)
print("\n A Sequential array with 10 values between 0 and 5:\n", i)

# Since the step (10) is larger than the range (0 to 5), 
# NumPy includes only the starting value 0 and then stops because the next value (10) is already greater than 5.

i = np.linspace(0,5,10)
print("\n A Sequential array with 10 values between 0 and 5:\n", i)

# using linspace, 10 values are created between 0 and 5
# np.arange(start, stop, step) → step size is specified.
# np.linspace(start, stop, num) → number of values is specified


 A Sequential array with 10 values between 0 and 5:
 [0]

 A Sequential array with 10 values between 0 and 5:
 [0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


### 8. Reshaping 3x4 array to 2x2x3 array

In [34]:
arr = np.array([[1,2,3,4],
               [5,2,3,2],
               [1,2,0,1]])
newArr = arr.reshape(2,2,3)
print("\n Original array:\n", arr)
print("\n Reshaped array:\n", newArr)


 Original array:
 [[1 2 3 4]
 [5 2 3 2]
 [1 2 0 1]]

 Reshaped array:
 [[[1 2 3]
  [4 5 2]]

 [[3 2 1]
  [2 0 1]]]


### 9. Flatten Array

In [35]:
arr = np.array([[1,2,3],[4,5,6]])
f1arr = arr.flatten()
print("\n Original Array:\n", arr)
print("\n Flattened Array:\n", f1arr)


 Original Array:
 [[1 2 3]
 [4 5 6]]

 Flattened Array:
 [1 2 3 4 5 6]


### 10. Create a null vector of size 10

In [36]:
null_vector = np.zeros(10)
print("Null vector with 10 zeros:\n", null_vector)

Null vector with 10 zeros:
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [37]:
null_vector = np.zeros(10, dtype=int)
print("Null vector with 10 zeros of int type:\n", null_vector)

Null vector with 10 zeros of int type:
 [0 0 0 0 0 0 0 0 0 0]


### 11.  How to find the memory size of any array

In [38]:
arr = np.array([1,2,3,4,5])
print(arr.nbytes)

print("Size of one element:", arr.itemsize, "bytes")
print("Number of elements:", arr.size)
print("Total memory:", arr.nbytes, "bytes")

# arr.nbytes == arr.size * arr.itemsize
# Total Memory = Number of Elements × Size of One Element

# Example with 2-D Array
arr = np.array([[1,2,3],
               [5,6,7]])
print(arr.nbytes)

print("Size of one element:", arr.itemsize)
print("Number of elements:", arr.size)
print("Total memory:", arr.nbytes)

40
Size of one element: 8 bytes
Number of elements: 5
Total memory: 40 bytes
48
Size of one element: 8
Number of elements: 6
Total memory: 48


### 12.  How to get the documentation of the numpy add function from the command line? 

In [39]:
help(np.add)
#np.add?
#np.add??

Help on ufunc in module numpy:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

    Add arguments element-wise.

    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

### 13.  Create a null vector of size 10 but the fifth value which is 1


In [40]:
arr = np.zeros(10, dtype=int)
arr[4] = 1   # NumPy uses 0-based indexing
print(arr)

[0 0 0 0 1 0 0 0 0 0]


### 14.  Create a vector with values ranging from 10 to 49

In [41]:
arr = np.arange(10,50)
print(arr)

# Starts from 10 and Stops before 50, so the last value is 49, increments by 1(default).
# np.arange(10,50) -> includes 10, excludes 50, output contains all integers from 10 to 49.

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


### 15.  Reverse a vector (first element becomes last)

In [42]:
arr = np.arange(10, 50)
reversed_arr = arr[::-1]
print(reversed_arr)

#Example 
arr = np.array([1,2,3,4,5])
reversed_arr = arr[::-1]
print(reversed_arr)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]
[5 4 3 2 1]


### 16.  Create a 3x3 matrix with values ranging from 0 to 8

In [43]:
arr = np.arange(9)
print(arr)

arr = np.arange(9).reshape(3,3)
print(arr)

# np.arange(9)      # Create 9 numbers (0–8)
# .reshape(3, 3)    # Arrange them into 3 rows and 3 columns

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


### 17. Find indices of non-zero elements from \[1,2,0,0,4,0\]

In [44]:
arr = np.array([1,2,0,0,4,0])
print(np.nonzero(arr))
# To find the indices of non-zero elements
print(np.nonzero(arr)[0])

(array([0, 1, 4]),)
[0 1 4]


### 18. Create a 3x3 identity matrix

In [45]:
arr = np.eye(3,3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### 19. Create a 3x3x3 array with random values

In [46]:
arr = np.random.random((3,3,3))
print(arr)

[[[0.44706073 0.32686346 0.02796683]
  [0.8186667  0.24286508 0.00465358]
  [0.033966   0.10877977 0.32175457]]

 [[0.43105204 0.96260364 0.71087872]
  [0.39480467 0.48814958 0.6220098 ]
  [0.9299573  0.41148762 0.04284587]]

 [[0.2224381  0.71371502 0.52814323]
  [0.9610985  0.20712697 0.54922762]
  [0.52257003 0.83909245 0.4067653 ]]]


### 20. Create a 10x10 array with random values and find the minimum and maximum values

In [47]:
arr = np.random.random((10,10))
print(arr)
Minimum = np.min(arr)
Maximum = np.max(arr)
print("Minimum of the random array is:", Minimum)
print("Maximum of the random array is:", Maximum)

[[0.2545617  0.372175   0.27781364 0.65200584 0.69284586 0.54360574
  0.98730112 0.52314426 0.27695711 0.19410316]
 [0.36599383 0.26292124 0.39532304 0.27806277 0.0623903  0.89389766
  0.42123944 0.28708484 0.45321026 0.21299872]
 [0.24402449 0.60517268 0.04247263 0.23901053 0.307472   0.71338557
  0.15402379 0.80495519 0.56944858 0.14917894]
 [0.04418849 0.51996672 0.65070584 0.34495954 0.07293451 0.4094102
  0.70295217 0.72862839 0.91707228 0.96046312]
 [0.29971259 0.59033041 0.22498067 0.49390138 0.81670131 0.66844467
  0.73622712 0.68544169 0.52973535 0.26092286]
 [0.40115952 0.94357684 0.42941189 0.55304324 0.80143335 0.93547818
  0.60640102 0.44453095 0.27050634 0.30684924]
 [0.01287846 0.1565147  0.51210811 0.21902166 0.29642646 0.63179424
  0.72803497 0.01551409 0.68546589 0.02650597]
 [0.33577206 0.9272636  0.62677198 0.00453372 0.19623634 0.68591756
  0.8163841  0.42117778 0.57356924 0.13155093]
 [0.40586262 0.15296729 0.69937278 0.37780939 0.32938928 0.50750923
  0.31008592 

### 21. Create a random vector of size 30 and find the mean value

In [48]:
arr = np.random.random((30))
print(arr)
print("Mean value :", np.mean(arr))

[0.67013588 0.72998954 0.25266328 0.30197551 0.37737763 0.55748911
 0.97162057 0.22255706 0.13240923 0.22537551 0.84338574 0.76706096
 0.60143105 0.34485034 0.63682549 0.00785578 0.59535259 0.55359823
 0.51708596 0.29426122 0.23512759 0.34033179 0.23116962 0.56813935
 0.38304419 0.71525097 0.03479265 0.31595757 0.7987585  0.62298347]
Mean value : 0.4616285463471097


### 22. Create a 2d array with 1 on the border and 0 inside

In [49]:
arr = np.ones((5,5), dtype=int)
arr[1:-1, 1:-1] = 0
print(arr)


[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


### 23. How to add a border (filled with 0's) around an existing array?

In [50]:
arr = np.ones((3,3), dtype=int)
new_arr = np.pad(arr, pad_width=1, mode='constant', constant_values=0)
print(arr)
print(new_arr)

[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[0 0 0 0 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 0 0 0 0]]


### 24. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [51]:
arr = np.diag([1,2,3,4], k=-1)
print(arr)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


### 25. Create a 8x8 matrix and fill it with a checkerboard pattern

In [52]:
arr = np.zeros((8,8), dtype=int)

arr[1::2, ::2] = 1
arr[::2, 1::2] = 1

print(arr)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### 26. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [53]:
index = np.unravel_index(99, (6,7,8))
print(index)

(np.int64(1), np.int64(5), np.int64(3))
